/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cb180838-d124-4e58-aef7-1685213e9e8e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BjfXixJv6",
    "aws_user_pools_web_client_id": "2c72oamt62n080ol2h6kk3bben",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kfrgogytnnbwnhrufgdnobvj3u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xyusnypnfjg6regkhlpbppar2i",
    "aws_user_files_s3_bucket": "amplifyapp55898ec682d9441481fc1d6fcb24ef1b154315-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
